/**
 * 8STA Motorsport Connector Catalogue — Product Data
 * Souriau / Eaton 8STA Series
 * Full product range based on real catalog contact arrangements (pages 6-20)
 *
 * Part number format: 8STA[shellType]-[shellSize]-[layout][contactType][orientation]
 *   shellType: 0 = flange receptacle, 1 = inline, 6 = plug
 *   contactType: P = pin, S = socket
 *   orientation: N = standard
 */

var PRODUCTS = [

  // =========================================================================
  // Shell Size 01 — Miniature push-pull (page 12)
  // =========================================================================
  {
    id: '8STA-001',
    partNumber: '8STA1-01-03SN',
    name: '8STA Shell 01 — 3-way Socket, Layout 03',
    shellSize: '01',
    contactCount: 3,
    contactSize: '26',
    wireGauge: 'AWG 26-30',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Push-Pull',
    weight: 1,
    description: 'Ultra-miniature 3-contact push-pull socket for the smallest wiring applications. Used for individual sensor connections where space and weight are critical.'
  },
  {
    id: '8STA-002',
    partNumber: '8STA6-01-03PN',
    name: '8STA Shell 01 — 3-way Plug, Layout 03',
    shellSize: '01',
    contactCount: 3,
    contactSize: '26',
    wireGauge: 'AWG 26-30',
    orientation: 'Plug',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Push-Pull',
    weight: 1,
    description: 'Ultra-miniature 3-contact push-pull plug. Mates with 8STA1-01-03SN for single-sensor connections and lightweight harness builds.'
  },
  {
    id: '8STA-003',
    partNumber: '8STA1-01-05SN',
    name: '8STA Shell 01 — 5-way Socket, Layout 05',
    shellSize: '01',
    contactCount: 5,
    contactSize: '26',
    wireGauge: 'AWG 26-30',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Push-Pull',
    weight: 1,
    description: '5-contact push-pull socket in the smallest 8STA shell. Ideal for multi-signal sensor pods, pit-lane communication links, and cockpit micro-harnesses.'
  },
  {
    id: '8STA-004',
    partNumber: '8STA6-01-05PN',
    name: '8STA Shell 01 — 5-way Plug, Layout 05',
    shellSize: '01',
    contactCount: 5,
    contactSize: '26',
    wireGauge: 'AWG 26-30',
    orientation: 'Plug',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Push-Pull',
    weight: 1,
    description: '5-contact push-pull plug. Mates with 8STA1-01-05SN for miniature multi-signal applications.'
  },

  // =========================================================================
  // Shell Size 02 — Miniature push-pull (page 14)
  // =========================================================================
  {
    id: '8STA-005',
    partNumber: '8STA1-02-05SN',
    name: '8STA Shell 02 — 5-way Socket, Layout 05',
    shellSize: '02',
    contactCount: 5,
    contactSize: '26',
    wireGauge: 'AWG 26-30',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Push-Pull',
    weight: 2,
    description: '5-contact socket in shell 02. Popular for steering wheel paddle shift, brake pressure sensors, and compact cockpit electronics.'
  },
  {
    id: '8STA-006',
    partNumber: '8STA6-02-05PN',
    name: '8STA Shell 02 — 5-way Plug, Layout 05',
    shellSize: '02',
    contactCount: 5,
    contactSize: '26',
    wireGauge: 'AWG 26-30',
    orientation: 'Plug',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Push-Pull',
    weight: 2,
    description: '5-contact plug mating with 8STA1-02-05SN socket. Miniature form factor for signal-level motorsport wiring.'
  },
  {
    id: '8STA-007',
    partNumber: '8STA1-02-06SN',
    name: '8STA Shell 02 — 6-way Socket, Layout 06',
    shellSize: '02',
    contactCount: 6,
    contactSize: '26',
    wireGauge: 'AWG 26-30',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Push-Pull',
    weight: 2,
    description: '6-contact socket in shell 02. Higher density option for the miniature shell, suitable for multi-sensor pods and dash switches.'
  },
  {
    id: '8STA-008',
    partNumber: '8STA1-02-35SN',
    name: '8STA Shell 02 — 3-way Socket, Layout 35 (#22D)',
    shellSize: '02',
    contactCount: 3,
    contactSize: '22D',
    wireGauge: 'AWG 22-26',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Push-Pull',
    weight: 2,
    description: '3-contact socket with larger #22D contacts (5A each) in miniature shell 02. Higher current capacity for power-sensor hybrid connections.'
  },

  // =========================================================================
  // Shell Size 04 (page 6)
  // =========================================================================
  {
    id: '8STA-009',
    partNumber: '8STA1-04-05SN',
    name: '8STA Shell 04 — 5-way Socket, Layout 05',
    shellSize: '04',
    contactCount: 5,
    contactSize: '26',
    wireGauge: 'AWG 26-30',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Push-Pull',
    weight: 3,
    description: '5-contact socket in shell 04 with service class M (1300V rated). Suitable for higher-voltage signal applications in compact form.'
  },
  {
    id: '8STA-010',
    partNumber: '8STA1-04-35SN',
    name: '8STA Shell 04 — 3-way Socket, Layout 35 (#22D)',
    shellSize: '04',
    contactCount: 3,
    contactSize: '22D',
    wireGauge: 'AWG 22-26',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Push-Pull',
    weight: 3,
    description: '3-contact #22D socket in shell 04. Available in fuel-immersible variant for fuel system sensors and tank-mounted electronics.'
  },

  // =========================================================================
  // Shell Size 06 (page 6)
  // =========================================================================
  {
    id: '8STA-011',
    partNumber: '8STA1-06-05SN',
    name: '8STA Shell 06 — 5-way Socket, Layout 05',
    shellSize: '06',
    contactCount: 5,
    contactSize: '26',
    wireGauge: 'AWG 26-30',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Push-Pull',
    weight: 5,
    description: '5-contact socket in shell 06. Versatile connector for cockpit electronics, dash switches, and steering wheel interfaces.'
  },
  {
    id: '8STA-012',
    partNumber: '8STA6-06-05PN',
    name: '8STA Shell 06 — 5-way Plug, Layout 05',
    shellSize: '06',
    contactCount: 5,
    contactSize: '26',
    wireGauge: 'AWG 26-30',
    orientation: 'Plug',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Push-Pull',
    weight: 5,
    description: '5-contact plug mating with 8STA1-06-05SN. Available in fuel-immersible variant.'
  },
  {
    id: '8STA-013',
    partNumber: '8STA1-06-06SN',
    name: '8STA Shell 06 — 6-way Socket, Layout 06 (#22D)',
    shellSize: '06',
    contactCount: 6,
    contactSize: '22D',
    wireGauge: 'AWG 22-26',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Push-Pull',
    weight: 5,
    description: '6-contact #22D socket in shell 06. Service class M (1300V). Ideal for combined power and signal in a compact package.'
  },
  {
    id: '8STA-014',
    partNumber: '8STA1-06-09SN',
    name: '8STA Shell 06 — 9-way Socket, Layout 09',
    shellSize: '06',
    contactCount: 9,
    contactSize: '26',
    wireGauge: 'AWG 26-30',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Push-Pull',
    weight: 5,
    description: '9-contact socket in shell 06. Higher pin count for multi-channel sensor groups and cockpit control panels.'
  },
  {
    id: '8STA-015',
    partNumber: '8STA1-06-12SN',
    name: '8STA Shell 06 — 12-way Socket, Layout 12 (HD)',
    shellSize: '06',
    contactCount: 12,
    contactSize: '26',
    wireGauge: 'AWG 26-30',
    orientation: 'Socket (Receptacle)',
    density: 'High Density',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Push-Pull',
    weight: 5,
    description: 'High-density 12-contact socket in compact shell 06. Maximum signal count for this form factor, suitable for data-intensive sensor clusters.'
  },
  {
    id: '8STA-016',
    partNumber: '8STA1-06-35SN',
    name: '8STA Shell 06 — 5-way Socket, Layout 35 (#22D)',
    shellSize: '06',
    contactCount: 5,
    contactSize: '22D',
    wireGauge: 'AWG 22-26',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Push-Pull',
    weight: 5,
    description: '5-contact #22D socket. Service class M, suited for higher-current signals and small actuator power feeds.'
  },
  {
    id: '8STA-017',
    partNumber: '8STA1-06-98SN',
    name: '8STA Shell 06 — 3-way Socket, Layout 98 (#20)',
    shellSize: '06',
    contactCount: 3,
    contactSize: '20',
    wireGauge: 'AWG 20-24',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Push-Pull',
    weight: 5,
    description: '3-contact #20 power socket in shell 06. Service class I (1800V). 8TA series variant for high-voltage power delivery in a miniature shell.'
  },

  // =========================================================================
  // Shell Size 08 — Bayonet coupling begins (page 6)
  // =========================================================================
  {
    id: '8STA-018',
    partNumber: '8STA0-08-01SN',
    name: '8STA Shell 08 — 1-way Socket, Layout 01 (#16)',
    shellSize: '08',
    contactCount: 1,
    contactSize: '16',
    wireGauge: 'AWG 16-20',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Crimp',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 8,
    description: 'Single #16 power contact in shell 08 (spec 801). Service class II (2300V). Used for individual high-current power feeds to starters, fuel pumps, and actuators.'
  },
  {
    id: '8STA-019',
    partNumber: '8STA6-08-01PN',
    name: '8STA Shell 08 — 1-way Plug, Layout 01 (#16)',
    shellSize: '08',
    contactCount: 1,
    contactSize: '16',
    wireGauge: 'AWG 16-20',
    orientation: 'Plug',
    density: 'Standard',
    variant: 'Crimp',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 8,
    description: 'Single #16 power plug. Mates with 8STA0-08-01SN for high-current single-circuit connections.'
  },

  // =========================================================================
  // Shell Size 10 (page 7)
  // =========================================================================
  {
    id: '8STA-020',
    partNumber: '8STA0-10-01SN',
    name: '8STA Shell 10 — 1-way Socket, Layout 01 (#12)',
    shellSize: '10',
    contactCount: 1,
    contactSize: '12',
    wireGauge: 'AWG 12-16',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 12,
    description: 'Single #12 power contact (23A) in shell 10. Service class II. For high-current single-feed applications such as starter motors.'
  },
  {
    id: '8STA-021',
    partNumber: '8STA0-10-02SN',
    name: '8STA Shell 10 — 2-way Socket, Layout 02 (#16)',
    shellSize: '10',
    contactCount: 2,
    contactSize: '16',
    wireGauge: 'AWG 16-20',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 12,
    description: '2-contact #16 socket (13A per pin). Service class I. For dual power feed applications such as twin fuel pump circuits.'
  },
  {
    id: '8STA-022',
    partNumber: '8STA0-10-04SN',
    name: '8STA Shell 10 — 4-way Socket, Layout 04 (#20)',
    shellSize: '10',
    contactCount: 4,
    contactSize: '20',
    wireGauge: 'AWG 20-24',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 12,
    description: '4-contact #20 socket (7.5A per pin). For medium-power multi-circuit connections to actuators and valves.'
  },
  {
    id: '8STA-023',
    partNumber: '8STA0-10-05SN',
    name: '8STA Shell 10 — 5-way Socket, Layout 05 (#20)',
    shellSize: '10',
    contactCount: 5,
    contactSize: '20',
    wireGauge: 'AWG 20-24',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 12,
    description: '5-contact #20 socket (7.5A per pin). Available in fuel-immersible variant. Popular for mixed power/signal actuator connections.'
  },
  {
    id: '8STA-024',
    partNumber: '8STA0-10-22SN',
    name: '8STA Shell 10 — 4-way Socket, Layout 22 (#22D)',
    shellSize: '10',
    contactCount: 4,
    contactSize: '22D',
    wireGauge: 'AWG 22-26',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 12,
    description: '4-contact #22D socket in shell 10. Service class M. Compact option for signal-level connections needing bayonet locking.'
  },
  {
    id: '8STA-025',
    partNumber: '8STA0-10-26SN',
    name: '8STA Shell 10 — 26-way Socket, Layout 26 (#26, HD)',
    shellSize: '10',
    contactCount: 26,
    contactSize: '26',
    wireGauge: 'AWG 26-30',
    orientation: 'Socket (Receptacle)',
    density: 'High Density',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 12,
    description: 'High-density 26-contact #26 socket in shell 10. Extreme signal density for data acquisition breakout and multi-channel sensor harnesses.'
  },
  {
    id: '8STA-026',
    partNumber: '8STA0-10-35SN',
    name: '8STA Shell 10 — 13-way Socket, Layout 35 (#22D)',
    shellSize: '10',
    contactCount: 13,
    contactSize: '22D',
    wireGauge: 'AWG 22-26',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 12,
    description: '13-contact #22D socket. Available in standard, hermetic, and fuel-immersible variants. Workhorse for engine sensors and mid-density signal harnesses.'
  },
  {
    id: '8STA-027',
    partNumber: '8STA6-10-35PN',
    name: '8STA Shell 10 — 13-way Plug, Layout 35 (#22D)',
    shellSize: '10',
    contactCount: 13,
    contactSize: '22D',
    wireGauge: 'AWG 22-26',
    orientation: 'Plug',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 12,
    description: '13-contact #22D plug. Mates with 8STA0-10-35SN for gearbox, engine, and drivetrain sensor connections.'
  },
  {
    id: '8STA-028',
    partNumber: '8STA0-10-80SN',
    name: '8STA Shell 10 — 1-way Socket, Layout 80 (#8)',
    shellSize: '10',
    contactCount: 1,
    contactSize: '8',
    wireGauge: 'AWG 8-12',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Crimp',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 12,
    description: 'Single #8 high-power contact (45A) in shell 10. Service class I. For high-current single-circuit applications such as starter motor feeds.'
  },
  {
    id: '8STA-029',
    partNumber: '8STA0-10-98SN',
    name: '8STA Shell 10 — 6-way Socket, Layout 98 (#20)',
    shellSize: '10',
    contactCount: 6,
    contactSize: '20',
    wireGauge: 'AWG 20-24',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 12,
    description: '6-contact #20 socket (7.5A per pin). Service class I. Available in hermetic and fuel-immersible variants.'
  },
  {
    id: '8STA-030',
    partNumber: '8STA0-10-99SN',
    name: '8STA Shell 10 — 7-way Socket, Layout 99 (#20)',
    shellSize: '10',
    contactCount: 7,
    contactSize: '20',
    wireGauge: 'AWG 20-24',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 12,
    description: '7-contact #20 socket. Maximum #20 contact count in shell 10 for multi-circuit power distribution.'
  },

  // =========================================================================
  // Shell Size 12 (page 7)
  // =========================================================================
  {
    id: '8STA-031',
    partNumber: '8STA0-12-01SN',
    name: '8STA Shell 12 — 1-way Socket, Layout 01 (#4)',
    shellSize: '12',
    contactCount: 1,
    contactSize: '4',
    wireGauge: 'AWG 4-8',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'PCB Mount',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 18,
    description: 'Single #4 high-power contact (80A) in shell 12. PCB mount variant (spec 261). For battery main feed, starter circuit, and high-current bus connections.'
  },
  {
    id: '8STA-032',
    partNumber: '8STA0-12-03SN',
    name: '8STA Shell 12 — 3-way Socket, Layout 03 (#16)',
    shellSize: '12',
    contactCount: 3,
    contactSize: '16',
    wireGauge: 'AWG 16-20',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 18,
    description: '3-contact #16 power socket (13A per pin). Service class I. For multi-phase power feeds and high-current distribution.'
  },
  {
    id: '8STA-033',
    partNumber: '8STA0-12-04SN',
    name: '8STA Shell 12 — 4-way Socket, Layout 04 (#16)',
    shellSize: '12',
    contactCount: 4,
    contactSize: '16',
    wireGauge: 'AWG 16-20',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 18,
    description: '4-contact #16 socket. Service class I. Available in hermetic variant for pressure-boundary applications.'
  },
  {
    id: '8STA-034',
    partNumber: '8STA0-12-08SN',
    name: '8STA Shell 12 — 8-way Socket, Layout 08 (#20)',
    shellSize: '12',
    contactCount: 8,
    contactSize: '20',
    wireGauge: 'AWG 20-24',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 18,
    description: '8-contact #20 socket (7.5A per pin). For multi-circuit power distribution to solenoids, valves, and actuator arrays.'
  },
  {
    id: '8STA-035',
    partNumber: '8STA0-12-26SN',
    name: '8STA Shell 12 — 8-way Socket, Layout 26 (mixed #22D/#12)',
    shellSize: '12',
    contactCount: 8,
    contactSize: '22D',
    wireGauge: 'AWG 12-26',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 18,
    description: 'Mixed layout: 6x #22D + 2x #12 contacts. Service class M. Combines signal and power in a single connector for intelligent actuators.'
  },
  {
    id: '8STA-036',
    partNumber: '8STA0-12-35SN',
    name: '8STA Shell 12 — 22-way Socket, Layout 35 (#22D)',
    shellSize: '12',
    contactCount: 22,
    contactSize: '22D',
    wireGauge: 'AWG 22-26',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 18,
    description: '22-contact #22D socket. Available in hermetic variant. Workhorse for engine and gearbox sensor harnesses.'
  },
  {
    id: '8STA-037',
    partNumber: '8STA6-12-35PN',
    name: '8STA Shell 12 — 22-way Plug, Layout 35 (#22D)',
    shellSize: '12',
    contactCount: 22,
    contactSize: '22D',
    wireGauge: 'AWG 22-26',
    orientation: 'Plug',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 18,
    description: '22-contact #22D plug. Mates with 8STA0-12-35SN for engine bay and drivetrain harness connections.'
  },
  {
    id: '8STA-038',
    partNumber: '8STA0-12-43SN',
    name: '8STA Shell 12 — 43-way Socket, Layout 43 (#26, HD)',
    shellSize: '12',
    contactCount: 43,
    contactSize: '26',
    wireGauge: 'AWG 26-30',
    orientation: 'Socket (Receptacle)',
    density: 'High Density',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 18,
    description: 'High-density 43-contact #26 socket. Maximum signal density in shell 12 for data-intensive applications.'
  },
  {
    id: '8STA-039',
    partNumber: '8STA0-12-98SN',
    name: '8STA Shell 12 — 10-way Socket, Layout 98 (#20)',
    shellSize: '12',
    contactCount: 10,
    contactSize: '20',
    wireGauge: 'AWG 20-24',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 18,
    description: '10-contact #20 socket. Available in hermetic and fuel-immersible variants. For power distribution and actuator harnesses.'
  },

  // =========================================================================
  // Shell Size 14 (page 8)
  // =========================================================================
  {
    id: '8STA-040',
    partNumber: '8STA0-14-05SN',
    name: '8STA Shell 14 — 5-way Socket, Layout 05 (#16)',
    shellSize: '14',
    contactCount: 5,
    contactSize: '16',
    wireGauge: 'AWG 16-20',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 24,
    description: '5-contact #16 power socket (13A per pin). Service class II (2300V). For multi-phase power and high-voltage distribution.'
  },
  {
    id: '8STA-041',
    partNumber: '8STA0-14-15SN',
    name: '8STA Shell 14 — 15-way Socket, Layout 15 (mixed #20/#16)',
    shellSize: '14',
    contactCount: 15,
    contactSize: '20',
    wireGauge: 'AWG 16-24',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 24,
    description: 'Mixed layout: 14x #20 + 1x #16. Service class I. Combines signal distribution with a single high-current power feed.'
  },
  {
    id: '8STA-042',
    partNumber: '8STA0-14-18SN',
    name: '8STA Shell 14 — 18-way Socket, Layout 18 (#20)',
    shellSize: '14',
    contactCount: 18,
    contactSize: '20',
    wireGauge: 'AWG 20-24',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 24,
    description: '18-contact #20 socket. Service class I. High contact count for multi-circuit power distribution and ECU connections.'
  },
  {
    id: '8STA-043',
    partNumber: '8STA0-14-19SN',
    name: '8STA Shell 14 — 19-way Socket, Layout 19 (#20)',
    shellSize: '14',
    contactCount: 19,
    contactSize: '20',
    wireGauge: 'AWG 20-24',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 24,
    description: '19-contact #20 socket. Maximum #20 count in shell 14. For PDM outputs and multi-actuator harnesses.'
  },
  {
    id: '8STA-044',
    partNumber: '8STA0-14-35SN',
    name: '8STA Shell 14 — 37-way Socket, Layout 35 (#22D)',
    shellSize: '14',
    contactCount: 37,
    contactSize: '22D',
    wireGauge: 'AWG 22-26',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 24,
    description: '37-contact #22D socket. Available in hermetic and fuel-immersible variants. Common for ECU main connectors and multi-channel sensor termination.'
  },
  {
    id: '8STA-045',
    partNumber: '8STA6-14-35PN',
    name: '8STA Shell 14 — 37-way Plug, Layout 35 (#22D)',
    shellSize: '14',
    contactCount: 37,
    contactSize: '22D',
    wireGauge: 'AWG 22-26',
    orientation: 'Plug',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 24,
    description: '37-contact #22D plug. Mates with 8STA0-14-35SN. Used on ECU housings and data logger enclosures.'
  },
  {
    id: '8STA-046',
    partNumber: '8STA0-14-68SN',
    name: '8STA Shell 14 — 68-way Socket, Layout 68 (#26, HD)',
    shellSize: '14',
    contactCount: 68,
    contactSize: '26',
    wireGauge: 'AWG 26-30',
    orientation: 'Socket (Receptacle)',
    density: 'High Density',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 24,
    description: 'High-density 68-contact #26 socket. Maximum signal count in shell 14 for data acquisition and high-channel-count harness junctions.'
  },
  {
    id: '8STA-047',
    partNumber: '8STA0-14-97SN',
    name: '8STA Shell 14 — 12-way Socket, Layout 97 (mixed #20/#16)',
    shellSize: '14',
    contactCount: 12,
    contactSize: '20',
    wireGauge: 'AWG 16-24',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 24,
    description: 'Mixed layout: 8x #20 + 4x #16. Service class I. Combines power and signal in a single connector for intelligent subsystems.'
  },

  // =========================================================================
  // Shell Size 16 (page 9)
  // =========================================================================
  {
    id: '8STA-048',
    partNumber: '8STA0-16-02SN',
    name: '8STA Shell 16 — 6-way Socket, Layout 02 (#12)',
    shellSize: '16',
    contactCount: 6,
    contactSize: '12',
    wireGauge: 'AWG 12-16',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 32,
    description: '6-contact #12 power socket (23A per pin). Service class I. For multi-phase high-current distribution.'
  },
  {
    id: '8STA-049',
    partNumber: '8STA0-16-08SN',
    name: '8STA Shell 16 — 8-way Socket, Layout 08 (#16)',
    shellSize: '16',
    contactCount: 8,
    contactSize: '16',
    wireGauge: 'AWG 16-20',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 32,
    description: '8-contact #16 socket (13A per pin). Service class II. For multi-circuit power distribution and PDM outputs.'
  },
  {
    id: '8STA-050',
    partNumber: '8STA0-16-11SN',
    name: '8STA Shell 16 — 11-way Socket, Layout 11 (#16)',
    shellSize: '16',
    contactCount: 11,
    contactSize: '16',
    wireGauge: 'AWG 16-20',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 32,
    description: '11-contact #16 socket. Service class II. High-count power layout for PDM connections and multi-channel power bus.'
  },
  {
    id: '8STA-051',
    partNumber: '8STA0-16-26SN',
    name: '8STA Shell 16 — 26-way Socket, Layout 26 (#20)',
    shellSize: '16',
    contactCount: 26,
    contactSize: '20',
    wireGauge: 'AWG 20-24',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 32,
    description: '26-contact #20 socket (7.5A per pin). Service class I. For high-count power/signal distribution in PDM and ECU harnesses.'
  },
  {
    id: '8STA-052',
    partNumber: '8STA0-16-32SN',
    name: '8STA Shell 16 — 32-way Socket, Layout 32 (#20)',
    shellSize: '16',
    contactCount: 32,
    contactSize: '20',
    wireGauge: 'AWG 20-24',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 32,
    description: '32-contact #20 socket. Maximum #20 count in shell 16 for high-density power/signal distribution.'
  },
  {
    id: '8STA-053',
    partNumber: '8STA0-16-35SN',
    name: '8STA Shell 16 — 55-way Socket, Layout 35 (#22D)',
    shellSize: '16',
    contactCount: 55,
    contactSize: '22D',
    wireGauge: 'AWG 22-26',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 32,
    description: '55-contact #22D socket. High signal density for complex harness junctions, PDM connections, and multi-function sensor modules.'
  },
  {
    id: '8STA-054',
    partNumber: '8STA6-16-35PN',
    name: '8STA Shell 16 — 55-way Plug, Layout 35 (#22D)',
    shellSize: '16',
    contactCount: 55,
    contactSize: '22D',
    wireGauge: 'AWG 22-26',
    orientation: 'Plug',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 32,
    description: '55-contact #22D plug. Mates with 8STA0-16-35SN for complex harness termination.'
  },
  {
    id: '8STA-055',
    partNumber: '8STA0-16-99SN',
    name: '8STA Shell 16 — 23-way Socket, Layout 99 (mixed #20/#16)',
    shellSize: '16',
    contactCount: 23,
    contactSize: '20',
    wireGauge: 'AWG 16-24',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 32,
    description: 'Mixed layout: 21x #20 + 2x #16. Service class I. Combines high signal count with power feed channels.'
  },

  // =========================================================================
  // Shell Size 18 (pages 9-10)
  // =========================================================================
  {
    id: '8STA-056',
    partNumber: '8STA0-18-16SN',
    name: '8STA Shell 18 — 16-way Socket, Layout 16 (#16)',
    shellSize: '18',
    contactCount: 16,
    contactSize: '16',
    wireGauge: 'AWG 16-20',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 40,
    description: '16-contact #16 power socket (13A per pin). Service class II. Heavy-duty power distribution for PDMs and power bus connections.'
  },
  {
    id: '8STA-057',
    partNumber: '8STA0-18-35SN',
    name: '8STA Shell 18 — 66-way Socket, Layout 35 (#22D)',
    shellSize: '18',
    contactCount: 66,
    contactSize: '22D',
    wireGauge: 'AWG 22-26',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 40,
    description: '66-contact #22D socket. High-density signal connector for main ECU harness connections and complex multi-channel sensor arrays.'
  },
  {
    id: '8STA-058',
    partNumber: '8STA6-18-35PN',
    name: '8STA Shell 18 — 66-way Plug, Layout 35 (#22D)',
    shellSize: '18',
    contactCount: 66,
    contactSize: '22D',
    wireGauge: 'AWG 22-26',
    orientation: 'Plug',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 40,
    description: '66-contact #22D plug. Mates with 8STA0-18-35SN for main ECU and data logger connections.'
  },
  {
    id: '8STA-059',
    partNumber: '8STA0-18-39SN',
    name: '8STA Shell 18 — 39-way Socket, Layout 39 (mixed #20/#16)',
    shellSize: '18',
    contactCount: 39,
    contactSize: '20',
    wireGauge: 'AWG 16-24',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 40,
    description: 'Mixed layout: 37x #20 + 2x #16. Service class I. High-count power/signal for PDM output harnesses.'
  },
  {
    id: '8STA-060',
    partNumber: '8STA0-18-41SN',
    name: '8STA Shell 18 — 41-way Socket, Layout 41 (#20)',
    shellSize: '18',
    contactCount: 41,
    contactSize: '20',
    wireGauge: 'AWG 20-24',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 40,
    description: '41-contact #20 socket. Maximum #20 count in shell 18 for comprehensive power distribution harnesses.'
  },
  {
    id: '8STA-061',
    partNumber: '8STA0-18-42SN',
    name: '8STA Shell 18 — 2-way Socket, Layout 42 (#4)',
    shellSize: '18',
    contactCount: 2,
    contactSize: '4',
    wireGauge: 'AWG 4-8',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'PCB Mount',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 40,
    description: 'Dual #4 high-power contacts (80A each). Service class I. For battery main feeds, high-current bus bars, and starter circuits.'
  },

  // =========================================================================
  // Shell Size 20 (page 10)
  // =========================================================================
  {
    id: '8STA-062',
    partNumber: '8STA0-20-11SN',
    name: '8STA Shell 20 — 11-way Socket, Layout 11 (#12)',
    shellSize: '20',
    contactCount: 11,
    contactSize: '12',
    wireGauge: 'AWG 12-16',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 50,
    description: '11-contact #12 power socket (23A per pin). Service class I. For heavy-duty multi-circuit power distribution.'
  },
  {
    id: '8STA-063',
    partNumber: '8STA0-20-21SN',
    name: '8STA Shell 20 — 21-way Socket, Layout 21 (#16)',
    shellSize: '20',
    contactCount: 21,
    contactSize: '16',
    wireGauge: 'AWG 16-20',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 50,
    description: '21-contact #16 socket (13A per pin). Service class II. For comprehensive PDM power distribution and high-current bus connections.'
  },
  {
    id: '8STA-064',
    partNumber: '8STA0-20-32SN',
    name: '8STA Shell 20 — 32-way Socket, Layout 32 (#20)',
    shellSize: '20',
    contactCount: 32,
    contactSize: '20',
    wireGauge: 'AWG 20-24',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 50,
    description: '32-contact #20 socket. Service class I. For multi-circuit power and signal distribution in large harnesses.'
  },
  {
    id: '8STA-065',
    partNumber: '8STA0-20-35SN',
    name: '8STA Shell 20 — 79-way Socket, Layout 35 (#22D)',
    shellSize: '20',
    contactCount: 79,
    contactSize: '22D',
    wireGauge: 'AWG 22-26',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 50,
    description: '79-contact #22D socket. High-density signal connector for main harness trunk connections, ECU breakout, and chassis wiring junctions.'
  },
  {
    id: '8STA-066',
    partNumber: '8STA6-20-35PN',
    name: '8STA Shell 20 — 79-way Plug, Layout 35 (#22D)',
    shellSize: '20',
    contactCount: 79,
    contactSize: '22D',
    wireGauge: 'AWG 22-26',
    orientation: 'Plug',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 50,
    description: '79-contact #22D plug. Mates with 8STA0-20-35SN for full-size harness junctions.'
  },
  {
    id: '8STA-067',
    partNumber: '8STA0-20-53SN',
    name: '8STA Shell 20 — 53-way Socket, Layout 53 (#20)',
    shellSize: '20',
    contactCount: 53,
    contactSize: '20',
    wireGauge: 'AWG 20-24',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 50,
    description: '53-contact #20 socket. Service class I. High-count #20 layout for comprehensive power/signal distribution in large harnesses.'
  },
  {
    id: '8STA-068',
    partNumber: '8STA0-20-55SN',
    name: '8STA Shell 20 — 55-way Socket, Layout 55 (#20)',
    shellSize: '20',
    contactCount: 55,
    contactSize: '20',
    wireGauge: 'AWG 20-24',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 50,
    description: '55-contact #20 socket. Maximum #20 count in shell 20 for the most demanding power distribution applications.'
  },
  {
    id: '8STA-069',
    partNumber: '8STA0-20-54SN',
    name: '8STA Shell 20 — 53-way Socket, Layout 54 (mixed #22D/#16/#12)',
    shellSize: '20',
    contactCount: 53,
    contactSize: '22D',
    wireGauge: 'AWG 12-26',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 50,
    description: 'Mixed layout: 40x #22D + 9x #16 + 4x #12. Service class M. For complex subsystems requiring signal, power, and high-power in one connector.'
  },
  {
    id: '8STA-070',
    partNumber: '8STA0-20-72SN',
    name: '8STA Shell 20 — 8-way Socket, Layout 72 (mixed #16/#4)',
    shellSize: '20',
    contactCount: 8,
    contactSize: '16',
    wireGauge: 'AWG 4-20',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 50,
    description: 'Mixed layout: 6x #16 + 2x #4. Service class I. Combines high-power feeds (80A) with control signals for motor controllers and inverters.'
  },

  // =========================================================================
  // Shell Size 22 (page 10)
  // =========================================================================
  {
    id: '8STA-071',
    partNumber: '8STA0-22-35SN',
    name: '8STA Shell 22 — 100-way Socket, Layout 35 (#22D)',
    shellSize: '22',
    contactCount: 100,
    contactSize: '22D',
    wireGauge: 'AWG 22-26',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 60,
    description: '100-contact #22D socket. The highest pin count in a single 8STA shell. Used for full ECU connectors and master harness junctions.'
  },
  {
    id: '8STA-072',
    partNumber: '8STA6-22-35PN',
    name: '8STA Shell 22 — 100-way Plug, Layout 35 (#22D)',
    shellSize: '22',
    contactCount: 100,
    contactSize: '22D',
    wireGauge: 'AWG 22-26',
    orientation: 'Plug',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 60,
    description: '100-contact #22D plug. Mates with 8STA0-22-35SN for the most demanding signal-count applications.'
  },

  // =========================================================================
  // Shell Size 24 (page 11) — largest shell
  // =========================================================================
  {
    id: '8STA-073',
    partNumber: '8STA0-24-04SN',
    name: '8STA Shell 24 — 56-way Socket, Layout 04 (mixed #20/#16)',
    shellSize: '24',
    contactCount: 56,
    contactSize: '20',
    wireGauge: 'AWG 16-24',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 72,
    description: 'Mixed layout: 48x #20 + 8x #16. Service class I. For comprehensive power and signal distribution in full chassis harnesses.'
  },
  {
    id: '8STA-074',
    partNumber: '8STA0-24-07SN',
    name: '8STA Shell 24 — 99-way Socket, Layout 07 (mixed #22D/#8)',
    shellSize: '24',
    contactCount: 99,
    contactSize: '22D',
    wireGauge: 'AWG 8-26',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 72,
    description: 'Mixed layout: 97x #22D + 2x #8. Service class M. Maximum signal density with integrated high-power feeds for smart harness junctions.'
  },
  {
    id: '8STA-075',
    partNumber: '8STA0-24-08SN',
    name: '8STA Shell 24 — 8-way Socket, Layout 08 (#8)',
    shellSize: '24',
    contactCount: 8,
    contactSize: '8',
    wireGauge: 'AWG 8-12',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Crimp',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 72,
    description: '8-contact #8 power socket (45A per pin, 360A total). Service class M. For heavy-duty multi-phase power distribution and motor connections.'
  },
  {
    id: '8STA-076',
    partNumber: '8STA0-24-19SN',
    name: '8STA Shell 24 — 19-way Socket, Layout 19 (#12)',
    shellSize: '24',
    contactCount: 19,
    contactSize: '12',
    wireGauge: 'AWG 12-16',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 72,
    description: '19-contact #12 power socket (23A per pin). Service class I. For multi-channel high-current distribution.'
  },
  {
    id: '8STA-077',
    partNumber: '8STA0-24-24SN',
    name: '8STA Shell 24 — 24-way Socket, Layout 24 (mixed #16/#12)',
    shellSize: '24',
    contactCount: 24,
    contactSize: '16',
    wireGauge: 'AWG 12-20',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 72,
    description: 'Mixed layout: 12x #16 + 12x #12. Service class II. For PDM power distribution combining 13A and 23A circuits.'
  },
  {
    id: '8STA-078',
    partNumber: '8STA0-24-29SN',
    name: '8STA Shell 24 — 29-way Socket, Layout 29 (#16)',
    shellSize: '24',
    contactCount: 29,
    contactSize: '16',
    wireGauge: 'AWG 16-20',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 72,
    description: '29-contact #16 socket (13A per pin). Service class I. For large-scale power distribution and multi-output PDMs.'
  },
  {
    id: '8STA-079',
    partNumber: '8STA0-24-35SN',
    name: '8STA Shell 24 — 128-way Socket, Layout 35 (#22D)',
    shellSize: '24',
    contactCount: 128,
    contactSize: '22D',
    wireGauge: 'AWG 22-26',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 72,
    description: '128-contact #22D socket — the highest pin count in the entire 8STA range. For full ECU connectors, master harness junctions, and high-channel data acquisition.'
  },
  {
    id: '8STA-080',
    partNumber: '8STA6-24-35PN',
    name: '8STA Shell 24 — 128-way Plug, Layout 35 (#22D)',
    shellSize: '24',
    contactCount: 128,
    contactSize: '22D',
    wireGauge: 'AWG 22-26',
    orientation: 'Plug',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 72,
    description: '128-contact #22D plug. Mates with 8STA0-24-35SN for the largest harness junction points and bulkhead pass-throughs.'
  },
  {
    id: '8STA-081',
    partNumber: '8STA0-24-37SN',
    name: '8STA Shell 24 — 37-way Socket, Layout 37 (#16)',
    shellSize: '24',
    contactCount: 37,
    contactSize: '16',
    wireGauge: 'AWG 16-20',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 72,
    description: '37-contact #16 socket. Maximum #16 count in shell 24. Service class I. For comprehensive power distribution.'
  },
  {
    id: '8STA-082',
    partNumber: '8STA0-24-41SN',
    name: '8STA Shell 24 — 41-way Socket, Layout 41 (mixed 5-size)',
    shellSize: '24',
    contactCount: 41,
    contactSize: '22D',
    wireGauge: 'AWG 8-26',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 72,
    description: 'Multi-size layout: 22x #22D + 3x #20 + 11x #16 + 2x #12 + 3x #8. Service class N. Full-spectrum connector for complex subsystems.'
  },
  {
    id: '8STA-083',
    partNumber: '8STA0-24-43SN',
    name: '8STA Shell 24 — 8-way Socket, Layout 43 (mixed #16/#4)',
    shellSize: '24',
    contactCount: 8,
    contactSize: '16',
    wireGauge: 'AWG 4-20',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 72,
    description: 'Mixed layout: 4x #16 + 4x #4. Service class I. High-power connector combining 80A feeds with control signals for motor/inverter connections.'
  },
  {
    id: '8STA-084',
    partNumber: '8STA0-24-44SN',
    name: '8STA Shell 24 — 43-way Socket, Layout 44 (mixed #20/#16)',
    shellSize: '24',
    contactCount: 43,
    contactSize: '20',
    wireGauge: 'AWG 16-24',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 72,
    description: 'Mixed layout: 23x #20 + 20x #16. Service class I. High-count combined power distribution for comprehensive harness connections.'
  },
  {
    id: '8STA-085',
    partNumber: '8STA0-24-46SN',
    name: '8STA Shell 24 — 46-way Socket, Layout 46 (mixed #20/#16/#8)',
    shellSize: '24',
    contactCount: 46,
    contactSize: '20',
    wireGauge: 'AWG 8-24',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 72,
    description: 'Mixed layout: 40x #20 + 4x #16 + 2x #8. Service class I. Combines signal, power, and high-power in a single large connector.'
  },
  {
    id: '8STA-086',
    partNumber: '8STA0-24-61SN',
    name: '8STA Shell 24 — 61-way Socket, Layout 61 (#20)',
    shellSize: '24',
    contactCount: 61,
    contactSize: '20',
    wireGauge: 'AWG 20-24',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 72,
    description: '61-contact #20 socket. Maximum #20 count in the 8STA range. For comprehensive power/signal distribution in full-vehicle harnesses.'
  },
  {
    id: '8STA-087',
    partNumber: '8STA6-24-61PN',
    name: '8STA Shell 24 — 61-way Plug, Layout 61 (#20)',
    shellSize: '24',
    contactCount: 61,
    contactSize: '20',
    wireGauge: 'AWG 20-24',
    orientation: 'Plug',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 72,
    description: '61-contact #20 plug. Mates with 8STA0-24-61SN for full-size power distribution harness junctions.'
  },

  // =========================================================================
  // Hermetic and Fuel-Immersible specialty variants
  // =========================================================================
  {
    id: '8STA-088',
    partNumber: '8STA0-10-35SN-H',
    name: '8STA Shell 10 — 13-way Socket, Layout 35 (#22D), Hermetic',
    shellSize: '10',
    contactCount: 13,
    contactSize: '22D',
    wireGauge: 'AWG 22-26',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Hermetic',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 12,
    description: 'Hermetically sealed 13-contact socket. Glass-to-metal seal prevents gas/fluid transfer. For pressure-boundary and clean-room applications.'
  },
  {
    id: '8STA-089',
    partNumber: '8STA0-10-35SN-F',
    name: '8STA Shell 10 — 13-way Socket, Layout 35 (#22D), Fuel Immersible',
    shellSize: '10',
    contactCount: 13,
    contactSize: '22D',
    wireGauge: 'AWG 22-26',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Fuel Immersible',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 12,
    description: 'Fuel-immersible 13-contact socket rated for direct fuel exposure. For fuel tank sender units, fuel pump assemblies, and endurance fuel systems.'
  },
  {
    id: '8STA-090',
    partNumber: '8STA0-14-35SN-H',
    name: '8STA Shell 14 — 37-way Socket, Layout 35 (#22D), Hermetic',
    shellSize: '14',
    contactCount: 37,
    contactSize: '22D',
    wireGauge: 'AWG 22-26',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Hermetic',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 24,
    description: 'Hermetically sealed 37-contact socket. Glass-to-metal seal for pressure-boundary ECU enclosures and sealed electronics housings.'
  },
  {
    id: '8STA-091',
    partNumber: '8STA0-14-35SN-F',
    name: '8STA Shell 14 — 37-way Socket, Layout 35 (#22D), Fuel Immersible',
    shellSize: '14',
    contactCount: 37,
    contactSize: '22D',
    wireGauge: 'AWG 22-26',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Fuel Immersible',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 24,
    description: 'Fuel-immersible 37-contact socket. Rated for direct fuel exposure in tank-mounted assemblies and fuel system electronics.'
  },
  {
    id: '8STA-092',
    partNumber: '8STA0-12-35SN-H',
    name: '8STA Shell 12 — 22-way Socket, Layout 35 (#22D), Hermetic',
    shellSize: '12',
    contactCount: 22,
    contactSize: '22D',
    wireGauge: 'AWG 22-26',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Hermetic',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 18,
    description: 'Hermetically sealed 22-contact socket in shell 12. Glass-to-metal seal for sealed ECU housings and pressure-boundary applications.'
  },
  {
    id: '8STA-093',
    partNumber: '8STA0-12-98SN-F',
    name: '8STA Shell 12 — 10-way Socket, Layout 98 (#20), Fuel Immersible',
    shellSize: '12',
    contactCount: 10,
    contactSize: '20',
    wireGauge: 'AWG 20-24',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Fuel Immersible',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 18,
    description: 'Fuel-immersible 10-contact #20 socket. For fuel pump assemblies and in-tank sensor harnesses in endurance racing applications.'
  },

  // =========================================================================
  // PCB Mount variants
  // =========================================================================
  {
    id: '8STA-094',
    partNumber: '8STA6-14-35PN-PCB',
    name: '8STA Shell 14 — 37-way Plug, Layout 35, PCB Mount',
    shellSize: '14',
    contactCount: 37,
    contactSize: '22D',
    wireGauge: 'AWG 22-26',
    orientation: 'Plug',
    density: 'Standard',
    variant: 'PCB Mount',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 24,
    description: '37-contact PCB mount plug. Solder-tail contacts for direct PCB integration on ECU housings, data loggers, and custom electronics.'
  },
  {
    id: '8STA-095',
    partNumber: '8STA6-16-35PN-PCB',
    name: '8STA Shell 16 — 55-way Plug, Layout 35, PCB Mount',
    shellSize: '16',
    contactCount: 55,
    contactSize: '22D',
    wireGauge: 'AWG 22-26',
    orientation: 'Plug',
    density: 'Standard',
    variant: 'PCB Mount',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 32,
    description: '55-contact PCB mount plug. For direct board integration in high-channel-count ECU and data acquisition enclosures.'
  },
  {
    id: '8STA-096',
    partNumber: '8STA6-24-35PN-PCB',
    name: '8STA Shell 24 — 128-way Plug, Layout 35, PCB Mount',
    shellSize: '24',
    contactCount: 128,
    contactSize: '22D',
    wireGauge: 'AWG 22-26',
    orientation: 'Plug',
    density: 'Standard',
    variant: 'PCB Mount',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55 to +175 C',
    coupling: 'Bayonet',
    weight: 72,
    description: '128-contact PCB mount plug. Maximum density PCB connector for full-feature ECU boards and master control units.'
  }
];

/**
 * Part Number Decoder Configuration
 * Maps each segment of the 8STA part number to selectable options.
 * Updated to cover all real shell sizes and contact arrangements.
 */
var DECODER_CONFIG = {
  shellSize: {
    label: 'Shell Size',
    options: [
      { value: '01', label: '01 (miniature)', series: '1' },
      { value: '02', label: '02 (miniature)', series: '1' },
      { value: '04', label: '04 (miniature)', series: '1' },
      { value: '06', label: '06 (miniature)', series: '1' },
      { value: '08', label: '08', series: '0' },
      { value: '10', label: '10', series: '0' },
      { value: '12', label: '12', series: '0' },
      { value: '14', label: '14', series: '0' },
      { value: '16', label: '16', series: '0' },
      { value: '18', label: '18', series: '0' },
      { value: '20', label: '20', series: '0' },
      { value: '22', label: '22', series: '0' },
      { value: '24', label: '24', series: '0' }
    ]
  },
  arrangement: {
    label: 'Insert Arrangement',
    options: [
      { value: '01', label: '01 — Single power contact' },
      { value: '02', label: '02 — 2-way / 6x #12' },
      { value: '03', label: '03 — 3-way' },
      { value: '04', label: '04 — 4-way / mixed #20+#16' },
      { value: '05', label: '05 — 5-way' },
      { value: '06', label: '06 — 6-way / mixed #22D+#8' },
      { value: '07', label: '07 — Mixed #22D+#8' },
      { value: '08', label: '08 — 8-way #20 / 8x #16' },
      { value: '09', label: '09 — 9-way' },
      { value: '11', label: '11 — 11-way #16 / #12' },
      { value: '12', label: '12 — 12-way' },
      { value: '15', label: '15 — 14x #20 + 1x #16' },
      { value: '16', label: '16 — 16x #16' },
      { value: '18', label: '18 — 18-way / mixed' },
      { value: '19', label: '19 — 19-way #20 / #12' },
      { value: '20', label: '20 — Mixed #20+#8' },
      { value: '21', label: '21 — 21x #16' },
      { value: '22', label: '22 — Mixed #12+#8' },
      { value: '24', label: '24 — 12x #16 + 12x #12' },
      { value: '26', label: '26 — 26-way #26 / #20' },
      { value: '28', label: '28 — 26x #20 + 2x #16' },
      { value: '29', label: '29 — 29x #16' },
      { value: '32', label: '32 — 32x #20' },
      { value: '35', label: '35 — Standard #22D (all sizes)' },
      { value: '37', label: '37 — 37x #16' },
      { value: '39', label: '39 — 37x #20 + 2x #16' },
      { value: '41', label: '41 — 41x #20 / mixed' },
      { value: '42', label: '42 — 2x #4' },
      { value: '43', label: '43 — 43x #26 / mixed #16+#4' },
      { value: '44', label: '44 — 23x #20 + 20x #16' },
      { value: '46', label: '46 — Mixed #20+#16+#8' },
      { value: '48', label: '48 — 4x #8' },
      { value: '53', label: '53 — 53x #20' },
      { value: '54', label: '54 — Mixed #22D+#16+#12' },
      { value: '55', label: '55 — 55x #20' },
      { value: '59', label: '59 — 55x #22D + 4x #12' },
      { value: '61', label: '61 — 61x #20' },
      { value: '68', label: '68 — 68x #26 (HD)' },
      { value: '72', label: '72 — 6x #16 + 2x #4' },
      { value: '75', label: '75 — 2-4x #8' },
      { value: '77', label: '77 — 17x #22D + 2x #8' },
      { value: '80', label: '80 — 1x #8' },
      { value: '97', label: '97 — 8x #20 + 4x #16' },
      { value: '98', label: '98 — Multi-way #20' },
      { value: '99', label: '99 — Mixed / #20' }
    ]
  },
  contactType: {
    label: 'Contact Type',
    options: [
      { value: 'S', label: 'S — Socket (Receptacle)' },
      { value: 'P', label: 'P — Pin (Plug)' }
    ]
  },
  variant: {
    label: 'Variant',
    options: [
      { value: '', label: 'Standard' },
      { value: 'H', label: 'H — Hermetic' },
      { value: 'F', label: 'F — Fuel Immersible' },
      { value: 'HD', label: 'HD — High Density' },
      { value: 'C', label: 'C — Crimp' },
      { value: 'PCB', label: 'PCB — PCB Mount' },
      { value: 'P', label: 'P — PCB Mount (spec 251)' }
    ]
  }
};
