/**
 * 8STA Motorsport Connector Catalogue — Product Data
 * Souriau / Eaton 8STA Series
 * 20 representative SKUs from the full 100+ range
 */

const PRODUCTS = [
  {
    id: '8STA-001',
    partNumber: '8STA1-02-35S',
    name: '8STA Shell 02 — 2 Pin Socket, Standard',
    shellSize: '02',
    contactCount: 2,
    contactSize: '26',
    wireGauge: 'AWG 24-30',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55°C to +175°C',
    coupling: 'Quick Mating (Bayonet)',
    weight: 2,
    description: 'Ultra-miniature 2-contact socket connector for space-constrained motorsport wiring. Ideal for single-sensor connections and lightweight harness builds.'
  },
  {
    id: '8STA-002',
    partNumber: '8STA1-02-35P',
    name: '8STA Shell 02 — 2 Pin Plug, Standard',
    shellSize: '02',
    contactCount: 2,
    contactSize: '26',
    wireGauge: 'AWG 24-30',
    orientation: 'Plug',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55°C to +175°C',
    coupling: 'Quick Mating (Bayonet)',
    weight: 2,
    description: 'Ultra-miniature 2-contact plug connector. Mates with 8STA1-02-35S socket for minimal-weight sensor and signal connections.'
  },
  {
    id: '8STA-003',
    partNumber: '8STA6-06-35S',
    name: '8STA Shell 06 — 6 Pin Socket, Standard',
    shellSize: '06',
    contactCount: 6,
    contactSize: '26',
    wireGauge: 'AWG 24-30',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55°C to +175°C',
    coupling: 'Quick Mating (Bayonet)',
    weight: 5,
    description: '6-contact socket in compact shell 06 form factor. Commonly used for steering wheel paddle shift, dash switches, and multi-sensor pods.'
  },
  {
    id: '8STA-004',
    partNumber: '8STA6-06-35P',
    name: '8STA Shell 06 — 6 Pin Plug, Standard',
    shellSize: '06',
    contactCount: 6,
    contactSize: '26',
    wireGauge: 'AWG 24-30',
    orientation: 'Plug',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55°C to +175°C',
    coupling: 'Quick Mating (Bayonet)',
    weight: 5,
    description: '6-contact plug mating with 8STA6-06-35S. Suitable for cockpit electronics and low-count signal distribution.'
  },
  {
    id: '8STA-005',
    partNumber: '8STA0-08-35S',
    name: '8STA Shell 08 — 7 Pin Socket, Standard',
    shellSize: '08',
    contactCount: 7,
    contactSize: '26',
    wireGauge: 'AWG 24-30',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55°C to +175°C',
    coupling: 'Quick Mating (Bayonet)',
    weight: 8,
    description: '7-contact standard density socket. Popular choice for gearbox sensors, lambda probes, and individual ECU sub-harness breakouts.'
  },
  {
    id: '8STA-006',
    partNumber: '8STA0-08-35P',
    name: '8STA Shell 08 — 7 Pin Plug, Standard',
    shellSize: '08',
    contactCount: 7,
    contactSize: '26',
    wireGauge: 'AWG 24-30',
    orientation: 'Plug',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55°C to +175°C',
    coupling: 'Quick Mating (Bayonet)',
    weight: 8,
    description: '7-contact standard density plug. Mates with 8STA0-08-35S for mid-range signal count applications.'
  },
  {
    id: '8STA-007',
    partNumber: '8STA0-08-35S-HD',
    name: '8STA Shell 08 — 12 Pin Socket, High Density',
    shellSize: '08',
    contactCount: 12,
    contactSize: '26',
    wireGauge: 'AWG 24-30',
    orientation: 'Socket (Receptacle)',
    density: 'High Density',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55°C to +175°C',
    coupling: 'Quick Mating (Bayonet)',
    weight: 8,
    description: 'High density 12-contact socket in shell 08 — nearly double the standard contact count. Maximises signal density for compact harness designs.'
  },
  {
    id: '8STA-008',
    partNumber: '8STA0-10-35S',
    name: '8STA Shell 10 — 5 Pin Socket, Standard (Power)',
    shellSize: '10',
    contactCount: 5,
    contactSize: '20',
    wireGauge: 'AWG 20-30',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55°C to +175°C',
    coupling: 'Quick Mating (Bayonet)',
    weight: 12,
    description: '5-contact socket with larger size 20 power contacts (1.0mm). Handles mixed power and signal in a single connector for actuators and pumps.'
  },
  {
    id: '8STA-009',
    partNumber: '8STA0-10-35P',
    name: '8STA Shell 10 — 5 Pin Plug, Standard (Power)',
    shellSize: '10',
    contactCount: 5,
    contactSize: '20',
    wireGauge: 'AWG 20-30',
    orientation: 'Plug',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55°C to +175°C',
    coupling: 'Quick Mating (Bayonet)',
    weight: 12,
    description: '5-contact plug with size 20 power contacts. Mates with 8STA0-10-35S for combined power and signal delivery.'
  },
  {
    id: '8STA-010',
    partNumber: '8STA0-10-35S-DD',
    name: '8STA Shell 10 — 26 Pin Socket, Double Density',
    shellSize: '10',
    contactCount: 26,
    contactSize: '26',
    wireGauge: 'AWG 24-30',
    orientation: 'Socket (Receptacle)',
    density: 'Double Density',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55°C to +175°C',
    coupling: 'Quick Mating (Bayonet)',
    weight: 12,
    description: 'Double density 26-contact socket in shell 10. Extreme signal density — 5x the standard contact count in the same envelope. Ideal for data acquisition breakout.'
  },
  {
    id: '8STA-011',
    partNumber: '8STA0-12-35S',
    name: '8STA Shell 12 — 10 Pin Socket, Standard',
    shellSize: '12',
    contactCount: 10,
    contactSize: '26',
    wireGauge: 'AWG 24-30',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55°C to +175°C',
    coupling: 'Quick Mating (Bayonet)',
    weight: 16,
    description: '10-contact standard socket in shell 12. Workhorse connector for engine sensors, gearbox interfaces, and mid-density wiring looms.'
  },
  {
    id: '8STA-012',
    partNumber: '8STA0-12-35P',
    name: '8STA Shell 12 — 10 Pin Plug, Standard',
    shellSize: '12',
    contactCount: 10,
    contactSize: '26',
    wireGauge: 'AWG 24-30',
    orientation: 'Plug',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55°C to +175°C',
    coupling: 'Quick Mating (Bayonet)',
    weight: 16,
    description: '10-contact standard plug. Mates with 8STA0-12-35S for engine bay and drivetrain harness connections.'
  },
  {
    id: '8STA-013',
    partNumber: '8STA0-14-35S',
    name: '8STA Shell 14 — 19 Pin Socket, Standard',
    shellSize: '14',
    contactCount: 19,
    contactSize: '26',
    wireGauge: 'AWG 24-30',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55°C to +175°C',
    coupling: 'Quick Mating (Bayonet)',
    weight: 22,
    description: '19-contact standard socket in shell 14. Common for ECU main connectors and multi-channel sensor harness termination.'
  },
  {
    id: '8STA-014',
    partNumber: '8STA0-14-35P-PCB',
    name: '8STA Shell 14 — 19 Pin Plug, PCB Mount',
    shellSize: '14',
    contactCount: 19,
    contactSize: '26',
    wireGauge: 'AWG 24-30',
    orientation: 'Plug',
    density: 'Standard',
    variant: 'PCB Mount',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55°C to +175°C',
    coupling: 'Quick Mating (Bayonet)',
    weight: 22,
    description: '19-contact PCB mount plug variant. Solder-tail contacts for direct PCB integration — used on ECU housings, data loggers, and custom electronics enclosures.'
  },
  {
    id: '8STA-015',
    partNumber: '8STA0-16-35S',
    name: '8STA Shell 16 — 22 Pin Socket, Standard',
    shellSize: '16',
    contactCount: 22,
    contactSize: '26',
    wireGauge: 'AWG 24-30',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55°C to +175°C',
    coupling: 'Quick Mating (Bayonet)',
    weight: 28,
    description: '22-contact standard socket. High pin count for complex harness junctions, PDM connections, and multi-function sensor modules.'
  },
  {
    id: '8STA-016',
    partNumber: '8STA0-20-35S',
    name: '8STA Shell 20 — 39 Pin Socket, Standard',
    shellSize: '20',
    contactCount: 39,
    contactSize: '26',
    wireGauge: 'AWG 26-30',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55°C to +175°C',
    coupling: 'Quick Mating (Bayonet)',
    weight: 38,
    description: '39-contact socket in shell 20. High-density signal connector for main harness trunk connections, ECU breakout, and chassis wiring junctions.'
  },
  {
    id: '8STA-017',
    partNumber: '8STA0-20-41S-FI',
    name: '8STA Shell 20 — 39 Pin Socket, Fuel Immersible',
    shellSize: '20',
    contactCount: 39,
    contactSize: '26',
    wireGauge: 'AWG 26-30',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Fuel Immersible',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55°C to +175°C',
    coupling: 'Quick Mating (Bayonet)',
    weight: 38,
    description: 'Fuel immersible 39-contact socket rated for direct fuel exposure. Used in fuel tank sender units, fuel pump assemblies, and endurance racing fuel systems.'
  },
  {
    id: '8STA-018',
    partNumber: '8STA0-24-35S',
    name: '8STA Shell 24 — 61 Pin Socket, Standard',
    shellSize: '24',
    contactCount: 61,
    contactSize: '26',
    wireGauge: 'AWG 26-30',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55°C to +175°C',
    coupling: 'Quick Mating (Bayonet)',
    weight: 52,
    description: '61-contact socket — the highest pin count in the 8STA range. Used for main ECU connectors, full chassis harness breakouts, and high-channel data acquisition.'
  },
  {
    id: '8STA-019',
    partNumber: '8STA0-24-35P',
    name: '8STA Shell 24 — 61 Pin Plug, Standard',
    shellSize: '24',
    contactCount: 61,
    contactSize: '26',
    wireGauge: 'AWG 26-30',
    orientation: 'Plug',
    density: 'Standard',
    variant: 'Standard',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55°C to +175°C',
    coupling: 'Quick Mating (Bayonet)',
    weight: 52,
    description: '61-contact plug mating with 8STA0-24-35S. Full-size connector for comprehensive harness junction points and bulkhead pass-throughs.'
  },
  {
    id: '8STA-020',
    partNumber: '8STA0-24-61S-HM',
    name: '8STA Shell 24 — 61 Pin Socket, Hermetic',
    shellSize: '24',
    contactCount: 61,
    contactSize: '26',
    wireGauge: 'AWG 26-30',
    orientation: 'Socket (Receptacle)',
    density: 'Standard',
    variant: 'Hermetic',
    bodyMaterial: 'Aluminium',
    plating: 'Black Zinc Nickel',
    matingCycles: 500,
    ipRating: 'IP67 (mated)',
    tempRange: '-55°C to +175°C',
    coupling: 'Quick Mating (Bayonet)',
    weight: 52,
    description: 'Hermetically sealed 61-contact socket for pressure-boundary applications. Glass-to-metal seal prevents gas or fluid transfer across bulkheads.'
  }
];

/**
 * Part Number Decoder Configuration
 * Maps each segment of the 8STA part number to selectable options
 */
const DECODER_CONFIG = {
  shellSize: {
    label: 'Shell Size',
    options: [
      { value: '02', label: '02', series: '1' },
      { value: '06', label: '06', series: '6' },
      { value: '08', label: '08', series: '0' },
      { value: '10', label: '10', series: '0' },
      { value: '12', label: '12', series: '0' },
      { value: '14', label: '14', series: '0' },
      { value: '16', label: '16', series: '0' },
      { value: '20', label: '20', series: '0' },
      { value: '24', label: '24', series: '0' }
    ]
  },
  arrangement: {
    label: 'Insert Arrangement',
    options: [
      { value: '35', label: '35 — Standard' },
      { value: '41', label: '41 — Alternate' },
      { value: '61', label: '61 — Alternate' }
    ]
  },
  contactType: {
    label: 'Contact Type',
    options: [
      { value: 'S', label: 'S — Socket' },
      { value: 'P', label: 'P — Plug' }
    ]
  },
  variant: {
    label: 'Variant',
    options: [
      { value: '', label: 'Standard' },
      { value: 'HD', label: 'HD — High Density' },
      { value: 'DD', label: 'DD — Double Density' },
      { value: 'PCB', label: 'PCB — PCB Mount' },
      { value: 'FI', label: 'FI — Fuel Immersible' },
      { value: 'HM', label: 'HM — Hermetic' }
    ]
  }
};
